package model

import (
	"bytes"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"go.nyet.org/xdfkit/kp"
)

// ReadKP parses a KP file into the model. name is the original file name
// for the provenance (may be empty).
func ReadKP(data []byte, name string) (*Model, error) {
	f, err := kp.Parse(data)
	if err != nil {
		return nil, err
	}
	m := FromKP(f)
	sum := sha256.Sum256(data)
	m.Provenance = &Provenance{Format: "kp", File: name, SHA256: hex.EncodeToString(sum[:])}
	return m, nil
}

// FromKP converts a parsed KP file. The KP fields the model doesn't carry are
// dropped; KP takes them from a template.
func FromKP(f *kp.File) *Model {
	p := &f.Project
	m := &Model{Schema: SchemaID, Project: Project{p.Name, p.Version}}
	folders := map[int32]bool{}
	for _, fd := range p.Folders {
		m.Categories = append(m.Categories, &Category{ID: int(fd.ID), Name: fd.Name})
		folders[fd.ID] = true
	}
	for _, km := range p.Maps {
		m.Objects = append(m.Objects, objectFromKP(km, folders[km.FolderID]))
	}
	m.assignKeys()
	return m
}

//go:embed empty.kp
var emptyKP []byte

//go:embed kp-defaults.json
var kpDefaultsJSON []byte

// kpDefaults holds, per layout ("v1", "v2") and record kind ("map", "axis",
// "slot" for undefined axes, "folder"), the commonest values in ecuxplot's
// packs of the KP fields the model doesn't carry (generated by the tests).
var kpDefaults = func() (d map[string]map[string]map[string]any) {
	dec := json.NewDecoder(bytes.NewReader(kpDefaultsJSON))
	dec.UseNumber()
	if err := dec.Decode(&d); err != nil {
		panic(err)
	}
	for _, recs := range d {
		for _, fields := range recs {
			for k, v := range fields {
				fields[k] = unhex(v)
			}
		}
	}
	return d
}()

// unhex turns the "0x..." strings that kp-defaults.json uses for round
// numbers into numbers. kp.Hex values are written without the prefix.
func unhex(v any) any {
	switch v := v.(type) {
	case string:
		if h, ok := strings.CutPrefix(v, "0x"); ok {
			if n, err := strconv.ParseInt(h, 16, 64); err == nil {
				return json.Number(strconv.FormatInt(n, 10))
			}
		}
	case []any:
		for i := range v {
			v[i] = unhex(v[i])
		}
	case map[string]any:
		for k := range v {
			v[k] = unhex(v[k])
		}
	}
	return v
}

// hexRound writes integers of at least 0x100 whose hex form is one digit
// followed by zeros, or all Fs, as "0x..." strings, so they read as the
// round numbers they are (kp-defaults.json).
func hexRound(v any) any {
	switch v := v.(type) {
	case json.Number:
		n, err := v.Int64()
		h := strings.TrimRight(strconv.FormatInt(n, 16), "0")
		if err == nil && n >= 0x100 && (len(h) == 1 || strings.Trim(h, "f") == "") {
			return fmt.Sprintf("0x%X", n)
		}
	case []any:
		for i := range v {
			v[i] = hexRound(v[i])
		}
	case map[string]any:
		for k := range v {
			v[k] = hexRound(v[k])
		}
	}
	return v
}

// KP converts the model to a KP file. Fields the model doesn't carry come from
// the template's map with the same key, or folder with the same id, and
// otherwise from kpDefaults; the file header and trailing data come from the
// template. A nil template means an empty WinOLS 2.24 project (v2). With the
// file the model was read from as template, KP reproduces it.
func (m *Model) KP(template *kp.File) (*kp.File, error) {
	if err := m.Check(); err != nil {
		return nil, err
	}
	t := template
	if t == nil {
		var err error
		if t, err = kp.Parse(emptyKP); err != nil {
			return nil, err
		}
		if m.Provenance != nil && m.Provenance.File != "" {
			t.Filename = m.Provenance.File
		}
	}
	d := kpDefaults[fmt.Sprintf("v%d", t.Layout())]
	f := *t
	f.Project.Name, f.Project.Version = m.Project.Name, m.Project.Version
	f.Project.Maps, f.Project.Folders = nil, nil

	tm := FromKP(t)
	folders := map[int]map[string]any{}
	for i, c := range tm.Categories {
		r, err := residue(t.Project.Folders[i], c.kpFolder())
		if err != nil {
			return nil, err
		}
		folders[c.ID] = r
	}
	maps := map[string]map[string]any{}
	for i, o := range tm.Objects {
		r, err := residue(t.Project.Maps[i], o.kpMap(i))
		if err != nil {
			return nil, err
		}
		maps[o.Key] = r
	}

	for _, c := range m.Categories {
		r, ok := folders[c.ID]
		if !ok {
			r = d["folder"]
		}
		fd := new(kp.Folder)
		if err := restore(fd, c.kpFolder(), r); err != nil {
			return nil, fmt.Errorf("category %d: %w", c.ID, err)
		}
		f.Project.Folders = append(f.Project.Folders, fd)
	}
	for i, o := range m.Objects {
		r, ok := maps[o.Key]
		if !ok {
			r = map[string]any{}
			for k, v := range d["map"] {
				r[k] = v
			}
			for k, x := range map[string]*Axis{"x": o.X, "y": o.Y} {
				if a := d[axisKind(x)]; a != nil {
					r[k] = a
				}
			}
		}
		km := new(kp.Map)
		if err := restore(km, o.kpMap(i), r); err != nil {
			return nil, fmt.Errorf("object %s: %w", o.Key, err)
		}
		km.Index = i
		f.Project.Maps = append(f.Project.Maps, km)
	}
	return &f, nil
}

func axisKind(x *Axis) string {
	if x == nil {
		return "slot"
	}
	return "axis"
}

func (c *Category) kpFolder() *kp.Folder { return &kp.Folder{ID: int32(c.ID), Name: c.Name} }

var shapes = map[kp.Org]string{kp.OrgSingle: "value", kp.OrgOneD: "1d", kp.OrgTwoD: "2d", kp.OrgTwoDInv: "2d"}

func objectFromKP(km *kp.Map, inFolder bool) *Object {
	o := &Object{
		ID:          km.ID,
		Description: km.Name,
		Comment:     km.Comment,
		Shape:       shapes[km.Organization],
		Inverse:     km.Organization == kp.OrgTwoDInv,
		Address:     Addr(km.Start),
		Rows:        int(km.Rows),
		Cols:        int(km.Cols),
		Data:        dataFromKP(km.Type, km.Signed),
		Value:       valueFromKP(km.Value, int(km.Precision), km.Reciprocal),
		View:        View{Base: int(km.Base), Difference: km.Difference, Percent: km.Percent},
		X:           axisFromKP(km.X),
		Y:           axisFromKP(km.Y),
	}
	if inFolder {
		o.Categories = []int{int(km.FolderID)}
	}
	switch {
	case o.Shape != "":
	case o.Rows > 1:
		o.Shape = "2d"
	case o.Cols > 1:
		o.Shape = "1d"
	default:
		o.Shape = "value"
	}
	return o
}

func (o *Object) kpMap(i int) *kp.Map {
	org := map[string]kp.Org{"value": kp.OrgSingle, "1d": kp.OrgOneD, "2d": kp.OrgTwoD}[o.Shape]
	if o.Inverse {
		org = kp.OrgTwoDInv
	}
	t := kpType(o.Data)
	km := &kp.Map{
		Index:        i,
		Comment:      o.Comment,
		Name:         o.Description,
		Organization: org,
		Type:         t,
		Width:        int32(t.Width()),
		Base:         int32(o.View.Base),
		ID:           o.ID,
		Reciprocal:   o.Value.Conversion.Reciprocal,
		Signed:       o.Data.Signed,
		Difference:   o.View.Difference,
		Percent:      o.View.Percent,
		Cols:         int32(o.Cols),
		Rows:         int32(o.Rows),
		Precision:    int32(o.Value.Precision),
		Value:        kpValue(o.Value),
		Start:        uint32(o.Address),
		End:          uint32(o.Address) + uint32(o.Rows*o.Cols*t.Width()),
		Addr2:        uint32(o.Address),
		X:            o.X.kpAxis(),
		Y:            o.Y.kpAxis(),
		YUnk06:       int32(o.Cols),
		YUnk0A:       int32(o.Rows),
		Term2:        kp.Hex{1, 1, 1},
	}
	if o.Inverse {
		km.YUnk06, km.YUnk0A = km.YUnk0A, km.YUnk06
	}
	if len(o.Categories) > 0 {
		km.FolderID = int32(o.Categories[0])
	}
	return km
}

func dataFromKP(t kp.Type, signed bool) Data {
	d := Data{Bits: 8 * t.Width(), Signed: signed, Float: t.Float()}
	if d.Bits == 0 {
		d.Bits = 8
	}
	if d.Bits > 8 {
		d.Endian = map[bool]string{true: "little", false: "big"}[t.LE()]
	}
	return d
}

func kpType(d Data) kp.Type {
	le := kp.Type(0)
	if d.Endian == "little" {
		le = 1
	}
	switch {
	case d.Bits == 16:
		return 2 + le
	case d.Bits == 32 && d.Float:
		return 6 + le
	case d.Bits == 32:
		return 4 + le
	}
	return 1
}

func valueFromKP(v kp.Value, precision int, reciprocal bool) Value {
	return Value{v.Description, v.Units, precision, Conversion{v.Factor, v.Offset, reciprocal}}
}

func kpValue(v Value) kp.Value {
	return kp.Value{Description: v.Description, Units: v.Units, Factor: v.Conversion.Factor, Offset: v.Conversion.Offset}
}

// Axis sources and storage by KP datasource (docs/kp-format.md). 4 and 5
// follow the WinOLS script enum order, unconfirmed.
var axisSources = []struct{ source, stored string }{
	kp.DSOrdinal:        {"ordinal", ""},
	kp.DSEeprom:         {"image", "absolute"},
	kp.DSEepromAdd:      {"image", "add"},
	kp.DSEepromSubtract: {"image", "subtract"},
	4:                   {"editable", ""},
	5:                   {"image", "backwards"},
}

const noSignature = -1

func axisFromKP(a *kp.Axis) *Axis {
	if a == nil || !a.Defined {
		return nil
	}
	x := &Axis{
		Source: "unknown",
		Value:  valueFromKP(a.Value, int(a.Precision), a.Reciprocal),
		View:   View{Base: int(a.Base)},
		Mirror: a.Mirror,
		Header: int(a.DataHeader),
	}
	if a.SignatureByte != noSignature {
		s := int(a.SignatureByte)
		x.Signature = &s
	}
	if ds := int(a.DataSource); ds >= 0 && ds < len(axisSources) {
		x.Source, x.Stored = axisSources[ds].source, axisSources[ds].stored
	}
	if x.Source == "image" {
		addr, d := Addr(a.Addr), dataFromKP(a.Type, a.Signed)
		x.Address, x.Data = &addr, &d
	}
	return x
}

// kpAxis rebuilds the axis record from the model. Width is derived from the
// type, as WinOLS stores it (docs/kp-format.md).
func (x *Axis) kpAxis() *kp.Axis {
	a := &kp.Axis{PrecisionUnk00: kp.Hex{0, 0, 0}, SignedUnk00: []int32{}}
	if x == nil {
		a.Value = kp.Value{Description: "-", Units: "-"} // as WinOLS fills unused slots
		return a
	}
	a.Defined = true
	a.Mirror = x.Mirror
	a.DataHeader = int32(x.Header)
	a.SignatureByte = noSignature
	if x.Signature != nil {
		a.SignatureByte = int32(*x.Signature)
	}
	a.Value = kpValue(x.Value)
	a.Reciprocal = x.Value.Conversion.Reciprocal
	a.Precision = byte(x.Value.Precision)
	a.Base = int32(x.View.Base)
	for ds, s := range axisSources {
		if s.source == x.Source && s.stored == x.Stored {
			a.DataSource = kp.DataSource(ds)
		}
	}
	if x.Address != nil {
		a.Addr = uint32(*x.Address)
	}
	if x.Data != nil {
		a.Type, a.Signed = kpType(*x.Data), x.Data.Signed
		a.Width = int32(a.Type.Width())
	}
	return a
}
