package kp

import (
	"encoding/hex"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"slices"
	"sort"
	"strconv"
	"strings"
	"testing"

	"go.nyet.org/xdfkit/internal/corpus"
	"go.nyet.org/xdfkit/internal/testenv"
)

// TestSurvey writes a survey of every undecoded (Unk) field over the archived
// packs and the local WinOLS saves, with their images, to the file named by
// XDFKIT_SURVEY (plans/70-kp-field-survey.sh). Skipped otherwise.
func TestSurvey(t *testing.T) {
	out := os.Getenv("XDFKIT_SURVEY")
	if out == "" {
		t.Skip("XDFKIT_SURVEY not set")
	}
	samples := surveyInputs(t)
	tables := map[string]*table{}
	for _, k := range []string{"file", "folder", "map", "axis"} {
		tables[k] = &table{cols: map[string]int{}}
	}
	for fi, s := range samples {
		r := tables["file"].row(fi)
		flatten(reflect.ValueOf(*s.f), "", r, "Project")
		flatten(reflect.ValueOf(s.f.Project), "project.", r, "Maps", "Folders")
		for _, fd := range s.f.Project.Folders {
			flatten(reflect.ValueOf(*fd), "", tables["folder"].row(fi), "")
		}
		for _, m := range s.f.Project.Maps {
			r := tables["map"].row(fi)
			flatten(reflect.ValueOf(*m), "", r, "X", "Y")
			flatten(reflect.ValueOf(*m.X), "x.", r, "")
			flatten(reflect.ValueOf(*m.Y), "y.", r, "")
			derive(r, m.Value.Factor, m.Value.Offset, s.img, m.Start, int(m.Cols*m.Rows), m.Type, m.Signed)
			for _, ax := range []struct {
				name string
				a    *Axis
				n    int32
			}{{"x", m.X, m.Cols}, {"y", m.Y, m.Rows}} {
				r := tables["axis"].row(fi)
				flatten(reflect.ValueOf(*ax.a), "", r, "")
				r.set("signedUnk00 (values)", leaf{s: listKind(ax.a.SignedUnk00, s.img, ax.a, int(ax.n))})
				r.set("slot", leaf{s: ax.name})
				r.set("points", num(float64(ax.n)))
				for _, k := range []string{"organization", "type", "cols", "rows", "start", "id"} {
					r.set("map."+k, tables["map"].get(tables["map"].rows[len(tables["map"].rows)-1], k))
				}
				if ax.a.DataSource.FromImage() {
					derive(r, ax.a.Value.Factor, ax.a.Value.Offset, s.img, ax.a.Addr, int(ax.n), ax.a.Type, ax.a.Signed)
				}
			}
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# KP field survey\n\nGenerated by `plans/70-kp-field-survey.sh` (`XDFKIT_SURVEY=... go test ./kp -run TestSurvey`); don't edit. Inputs:\n\n")
	for _, s := range samples {
		img := "no image"
		if s.img != nil {
			img = fmt.Sprintf("image %d bytes", len(s.img))
		}
		fmt.Fprintf(&b, "- `%s`: v%d, %d maps, %d folders, %s\n", s.label, s.f.Layout(), len(s.f.Project.Maps), len(s.f.Project.Folders), img)
	}
	b.WriteString("\nPer field: distinct values per layout with the commonest; how many files it varies within; for fields with a commonest value (the default), the named fields equal to it on non-default records, other fields non-default on the same records, and examples.\n")
	for _, k := range []string{"file", "folder", "map", "axis"} {
		tables[k].report(&b, k, samples)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
}

type sample struct {
	label string
	f     *File
	img   []byte
}

// surveyInputs returns the archived packs (without their dated copies) and the
// WinOLS saves in testdata/local, each with its image where one is found.
func surveyInputs(t *testing.T) []sample {
	root := testenv.ModuleRoot()
	arch := testenv.Archive(t)
	cdir := corpus.Dir()
	names := map[string]string{}
	tsv, _ := os.ReadFile(filepath.Join(arch, "images.tsv"))
	for _, l := range strings.Split(string(tsv), "\n") {
		if s, n, ok := strings.Cut(l, "\t"); ok {
			names[s] = n
		}
	}
	image := func(stem string) []byte {
		if b, err := os.ReadFile(filepath.Join(arch, stem+".bin")); err == nil {
			return b
		}
		b, _ := os.ReadFile(filepath.Join(cdir, "images", names[stem]+".bin"))
		return b
	}
	stemOf := func(file string) string {
		best := ""
		for s := range names {
			if strings.HasPrefix(file, s) && len(s) > len(best) {
				best = s
			}
		}
		return best
	}
	var out []sample
	add := func(label, path, stem string) {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		f, err := Parse(data)
		if err != nil {
			t.Fatalf("%s: %v", path, err)
		}
		out = append(out, sample{label, f, image(stem)})
	}
	dated := regexp.MustCompile(`-\d{8}\.kp$`)
	for _, p := range testenv.Packs(t) {
		if !dated.MatchString(p) {
			add(filepath.Base(p), p, strings.TrimSuffix(filepath.Base(p), ".kp"))
		}
	}
	local := filepath.Join(root, "testdata", "local")
	for _, g := range []struct{ glob, image string }{
		{"outgoing/w*.kp", "8D0907551M"},
		{"incoming/sweep/*.kp", "8D0907551M"},
		{"incoming/imported/*.kp", ""},
	} {
		ps, _ := filepath.Glob(filepath.Join(local, g.glob))
		for _, p := range ps {
			img := g.image
			if img == "" {
				img = stemOf(filepath.Base(p))
			}
			add("local/"+filepath.Base(p)+" (WinOLS 2.24 save of "+img+")", p, img)
		}
	}
	return out
}

type leaf struct {
	n     float64
	s     string
	isNum bool
	float bool
	set   bool
}

func num(f float64) leaf { return leaf{n: f, isNum: true, float: f != math.Trunc(f), set: true} }

func (l leaf) String() string {
	switch {
	case !l.isNum:
		return l.s
	case l.float:
		return strconv.FormatFloat(l.n, 'g', -1, 64)
	}
	return strconv.FormatFloat(l.n, 'f', -1, 64)
}

func (l leaf) eq(o leaf) bool {
	if l.isNum != o.isNum {
		return false
	}
	if !l.isNum {
		return l.s == o.s
	}
	return math.Abs(l.n-o.n) <= 1e-6*math.Max(1, math.Abs(o.n))
}

type table struct {
	cols  map[string]int
	order []string
	rows  []*rec
}

type rec struct {
	t    *table
	file int
	v    []leaf
}

func (t *table) row(file int) *rec {
	r := &rec{t: t, file: file}
	t.rows = append(t.rows, r)
	return r
}

func (t *table) get(r *rec, k string) leaf {
	i, ok := t.cols[k]
	if !ok || i >= len(r.v) {
		return leaf{}
	}
	return r.v[i]
}

func (r *rec) set(k string, l leaf) {
	i, ok := r.t.cols[k]
	if !ok {
		i = len(r.t.order)
		r.t.cols[k] = i
		r.t.order = append(r.t.order, k)
	}
	for len(r.v) <= i {
		r.v = append(r.v, leaf{})
	}
	l.set = true
	r.v[i] = l
}

// flatten sets every exported field of v under its JSON name, arrays element by
// element, skipping the fields named in skip.
func flatten(v reflect.Value, prefix string, r *rec, skip ...string) {
	ty := v.Type()
	for i := range ty.NumField() {
		f := ty.Field(i)
		if !f.IsExported() || slices.Contains(skip, f.Name) {
			continue
		}
		name, _, _ := strings.Cut(f.Tag.Get("json"), ",")
		leafOf(v.Field(i), prefix+name, r)
	}
}

func leafOf(v reflect.Value, path string, r *rec) {
	switch v.Kind() {
	case reflect.Struct:
		flatten(v, path+".", r)
	case reflect.Array:
		for i := range v.Len() {
			leafOf(v.Index(i), fmt.Sprintf("%s[%d]", path, i), r)
		}
	case reflect.Slice:
		if b, ok := v.Interface().(Hex); ok {
			s := hex.EncodeToString(b)
			if len(s) > 48 {
				s = fmt.Sprintf("%s... (%d bytes)", s[:48], len(b))
			}
			r.set(path, leaf{s: s})
		} else {
			r.set(path+" (length)", num(float64(v.Len())))
		}
	case reflect.Bool:
		if v.Bool() {
			r.set(path, num(1))
		} else {
			r.set(path, num(0))
		}
	case reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Int:
		r.set(path, num(float64(v.Int())))
	case reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		r.set(path, num(float64(v.Uint())))
	case reflect.Float32, reflect.Float64:
		l := num(v.Float())
		l.float = true
		r.set(path, l)
	case reflect.String:
		r.set(path, leaf{s: v.String()})
	}
}

// derive adds values computed from the scaling and the image: 1/factor, and
// the raw and physical minimum and maximum of the n values at addr.
func derive(r *rec, factor, offset float64, img []byte, addr uint32, n int, ty Type, signed bool) {
	if factor != 0 {
		r.set("(1/factor)", num(1/factor))
	}
	w := ty.Width()
	if img == nil || w == 0 || n <= 0 || uint64(addr)+uint64(n*w) > uint64(len(img)) {
		return
	}
	lo, hi := math.Inf(1), math.Inf(-1)
	for i := range n {
		b := img[int(addr)+i*w : int(addr)+(i+1)*w]
		var u uint64
		for j := range w {
			k := j
			if !ty.LE() {
				k = w - 1 - j
			}
			u |= uint64(b[k]) << (8 * j)
		}
		var x float64
		switch {
		case ty.Float():
			x = float64(math.Float32frombits(uint32(u)))
		case signed && u&(1<<(8*w-1)) != 0:
			x = float64(int64(u) - int64(1)<<(8*w))
		default:
			x = float64(u)
		}
		lo, hi = math.Min(lo, x), math.Max(hi, x)
	}
	r.set("(raw min)", num(lo))
	r.set("(raw max)", num(hi))
	r.set("(min)", num(lo*factor+offset))
	r.set("(max)", num(hi*factor+offset))
}

// listKind describes an axis's SignedUnk00 values: empty, all zero, the
// ordinal 1..n, equal to the raw axis values in the image, or the first few.
func listKind(v []int32, img []byte, a *Axis, n int) string {
	if len(v) == 0 {
		return "empty"
	}
	zero, ordinal, image := true, true, a.DataSource.FromImage() && img != nil && len(v) == n
	w := a.Type.Width()
	for i, x := range v {
		zero = zero && x == 0
		ordinal = ordinal && x == int32(i+1)
		if image {
			off := int(a.Addr) + i*w
			if w == 0 || off+w > len(img) {
				image = false
				continue
			}
			var u int64
			for j := range w {
				k := j
				if !a.Type.LE() {
					k = w - 1 - j
				}
				u |= int64(img[off+k]) << (8 * j)
			}
			image = int64(x) == u
		}
	}
	switch {
	case zero:
		return "zeros"
	case ordinal:
		return "ordinal"
	case image:
		return "image values"
	}
	s := fmt.Sprint(v[:min(len(v), 6)])
	if len(v) > 6 {
		s += "..."
	}
	return s
}

func isUnk(path string) bool {
	last := path[strings.LastIndex(path, ".")+1:]
	return (strings.Contains(last, "Unk") || strings.HasPrefix(last, "unk")) && !strings.HasPrefix(last, "unkHeader") && !strings.HasPrefix(last, "unkTrailing")
}

type count struct {
	v leaf
	n int
}

func histogram(rows []*rec, i int) []count {
	idx := map[string]int{}
	var cs []count
	for _, r := range rows {
		if i >= len(r.v) || !r.v[i].set {
			continue
		}
		k := r.v[i].String()
		j, ok := idx[k]
		if !ok {
			j = len(cs)
			idx[k] = j
			cs = append(cs, count{v: r.v[i]})
		}
		cs[j].n++
	}
	sort.SliceStable(cs, func(a, b int) bool { return cs[a].n > cs[b].n })
	return cs
}

func top(cs []count, k int) string {
	var s []string
	for i, c := range cs {
		if i == k {
			s = append(s, fmt.Sprintf("%d more", len(cs)-k))
			break
		}
		s = append(s, fmt.Sprintf("`%s` %d", c.v, c.n))
	}
	return strings.Join(s, ", ")
}

func (t *table) report(b *strings.Builder, kind string, samples []sample) {
	files := map[int]bool{}
	for _, r := range t.rows {
		files[r.file] = true
	}
	fmt.Fprintf(b, "\n## %s records\n\n%d records in %d files.\n", kind, len(t.rows), len(files))
	defaults := make([]leaf, len(t.order))
	for i := range t.order {
		if cs := histogram(t.rows, i); len(cs) > 0 {
			defaults[i] = cs[0].v
		}
	}
	for i, path := range t.order {
		if !isUnk(path) {
			continue
		}
		fmt.Fprintf(b, "\n### `%s`\n\n", path)
		for _, l := range []Layout{V1, V2} {
			var rs []*rec
			for _, r := range t.rows {
				if samples[r.file].f.Layout() == l {
					rs = append(rs, r)
				}
			}
			if cs := histogram(rs, i); len(cs) > 0 {
				fmt.Fprintf(b, "- v%d: %d distinct: %s\n", l, len(cs), top(cs, 6))
			}
		}
		varies := 0
		for f := range files {
			var rs []*rec
			for _, r := range t.rows {
				if r.file == f {
					rs = append(rs, r)
				}
			}
			if len(histogram(rs, i)) > 1 {
				varies++
			}
		}
		fmt.Fprintf(b, "- varies within %d of %d files\n", varies, len(files))
		var odd []*rec
		for _, r := range t.rows {
			if i < len(r.v) && r.v[i].set && !r.v[i].eq(defaults[i]) {
				odd = append(odd, r)
			}
		}
		if len(odd) == 0 || len(odd) == len(t.rows) {
			continue
		}
		fmt.Fprintf(b, "- %d records differ from `%s`\n", len(odd), defaults[i])
		type score struct {
			path string
			f    float64
		}
		var eqs, codef []score
		varied := len(histogram(odd, i)) > 1
		for j, other := range t.order {
			if j == i {
				continue
			}
			same, both := 0, 0
			for _, r := range odd {
				if j < len(r.v) && r.v[j].set && r.v[i].eq(r.v[j]) {
					same++
				}
				if j < len(r.v) && r.v[j].set && !r.v[j].eq(defaults[j]) {
					both++
				}
			}
			// Equality means something only where both sides vary.
			if varied && !isUnk(other) && r2(same, len(odd)) >= 0.5 && len(histogram(odd, j)) > 1 {
				eqs = append(eqs, score{other, r2(same, len(odd))})
			}
			if both == len(odd) || r2(both, len(odd)) >= 0.95 {
				oddOther := 0
				for _, r := range t.rows {
					if j < len(r.v) && r.v[j].set && !r.v[j].eq(defaults[j]) {
						oddOther++
					}
				}
				if r2(both, oddOther) >= 0.95 {
					codef = append(codef, score{other, r2(both, len(odd))})
				}
			}
		}
		sort.SliceStable(eqs, func(a, b int) bool { return eqs[a].f > eqs[b].f })
		var s []string
		for k, e := range eqs {
			if k == 5 {
				break
			}
			s = append(s, fmt.Sprintf("`%s` %.0f%%", e.path, 100*e.f))
		}
		if len(s) > 0 {
			fmt.Fprintf(b, "- equal on those records to: %s\n", strings.Join(s, ", "))
		}
		s = nil
		for k, e := range codef {
			if k == 8 {
				s = append(s, fmt.Sprintf("%d more", len(codef)-k))
				break
			}
			s = append(s, fmt.Sprintf("`%s`", e.path))
		}
		if len(s) > 0 {
			fmt.Fprintf(b, "- non-default on the same records: %s\n", strings.Join(s, ", "))
		}
		b.WriteString("- examples:")
		for k, r := range odd {
			if k == 5 {
				break
			}
			ex := []string{samples[r.file].label[:min(len(samples[r.file].label), 12)]}
			for _, c := range []string{"id", "map.id", "name", "value.factor", "value.offset", "value.units", "organization", "map.organization", "slot", "dataSource"} {
				if l := t.get(r, c); l.set && l.String() != "" {
					ex = append(ex, c+"="+l.String())
				}
			}
			fmt.Fprintf(b, " [`%s` %s]", r.v[i], strings.Join(ex, " "))
		}
		b.WriteString("\n")
	}
}

func r2(a, b int) float64 {
	if b == 0 {
		return 0
	}
	return float64(a) / float64(b)
}
